# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '主机组信息',
                'verbose_name_plural': '主机组信息',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('ip', models.CharField(max_length=32, verbose_name='IP地址')),
                ('os', models.CharField(max_length=32, verbose_name='操作系统')),
                ('mem', models.CharField(max_length=128, verbose_name='内存')),
                ('disk', models.CharField(max_length=256, verbose_name='磁盘')),
                ('physical_cpu', models.PositiveSmallIntegerField(verbose_name='CPU物理核数')),
                ('logical_cpu', models.PositiveSmallIntegerField(verbose_name='CPU逻辑核数')),
                ('serialnumber', models.CharField(max_length=80, unique=True, verbose_name='序列号')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('idc', models.CharField(max_length=40, verbose_name='所属机房')),
                ('cabinet', models.CharField(max_length=32, verbose_name='机柜位置')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
                ('group', models.ManyToManyField(blank=True, null=True, to='develop_app.Group', verbose_name='组名')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
            },
        ),
    ]
